# Generated by Django 3.2.6 on 2021-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_label',
            field=models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('READ_WRITE', 'Read and Write'), ('NONE', 'None')], default='READ', max_length=100),
        ),
    ]
