# Generated by Django 3.2.6 on 2021-08-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_access_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_label',
        ),
    ]
