# Generated by Django 3.2.6 on 2021-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_invoice_invoiceItem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_on',
            field=models.DateField(null=True),
        ),
    ]
