# Generated by Django 3.2.6 on 2021-08-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_price_stock_amount'),
        ('invoice', '0004_amount_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='store.store'),
        ),
    ]
